
name: print secret
on:
  workflow_dispatch:
    

jobs:
  publish:
    runs-on: [ self-hosted, glcp-lvs-infosight ]
    steps:

    - name: secret
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: is-smtp.nimblestorage.com
        server_port: 25
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        #subject: ${{ github.job }} job ofor the repo ${{ steps.check_merge_conflicts.outputs.repo-name }} is ${{ job.status }}. Please fix the conflictsf ${{ matrix.repo_names }} is ${{ job.status }}
        subject: The value of the secret
        # email body as text
        #body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ matrix.repo_names }} is ${{ job.status }}
        body: >- 
              The value of the secret CCS_UPDATECTL_KEY is  ${{ secrets.CCS_UPDATECTL_KEY }}
              The value of the secret CCS_UPDATECTL_SERVER is  ${{ secrets.CCS_UPDATECTL_SERVER }}
              The value of the secret CCS_UPDATECTL_USER is  ${{ secrets.CCS_UPDATECTL_USER }}
        # comma-separated string, send email to
        to: chandra.guttapalli@hpe.com
        # from email name
        from: do-not-reply-Github-Actions
