name: Lint Code Base

on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: write    # This is required for actions/checkout
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_LOG_FILE: true
          LOG_FILE: super-linter.log
          LOG_LEVEL: ERROR

      - name: Upload Lint report
        uses: actions/upload-artifact@v3
        with:
          name: super-linter.log
          path: super-linter.log
          
  Lint-Code-Base:
    needs: lint-operations
    uses: githubactions-omkar/repo-1/.github/workflows/reusable-lint.yaml@main
    with:
      head_branch: ${{ github.head_ref }}
      target_branch: ${{ github.base_ref }}
      lint_logfile_name: super-linter.log
      lint_logfile_path: super-linter.log
